### PR TITLE
Update spoor.server.services.js

### PR DESCRIPTION
**Pull request by tom-parker**

### CODE REVIEW

**Comment by j-mes** [comment]
@andygout Yep, all cool with me :+1:

**Comment by j-mes** [comment]
I would presume so, unless its elsewhere to grab the headers from?

**Comment by andygout** [comment]
From @tom-parker:

```
[146] $ node -e 'const url = require("url"); console.log(url.parse("scout.asia"));'
Url {
  protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  search: null,
  query: null,
  pathname: 'scout.asia',
  path: 'scout.asia',
  href: 'scout.asia' }
```

```
$ node -e 'const url = require("url"); console.log(url.parse("http://scout.asia"));'
Url {
  protocol: 'http:',
  slashes: true,
  auth: null,
  host: 'scout.asia',
  port: null,
  hostname: 'scout.asia',
  hash: null,
  search: null,
  query: null,
  pathname: '/',
  path: '/',
  href: 'http://scout.asia/' }
```

> The filtering logic uses url.parse and then looks at hostname in the returned object
> without the `http://` on the front hostname is null

**Comment by andygout** [comment]
For `'https://app.scout.asia';`, the output from `url.parse()` will be:

```
Url {
  protocol: 'https:',
  slashes: true,
  auth: null,
  host: 'app.scout.asia',
  port: null,
  hostname: 'app.scout.asia',
  hash: null,
  search: null,
  query: null,
  pathname: '/',
  path: '/',
  href: 'https://app.scout.asia/' }
```

So `app.scout.asia` will be read by this line: https://github.com/Financial-Times/spoor-enrichment/blob/master/server/filters/discard-bad-events.js#L22 and be `true` on this basis: `'app.scout.asia'.indexOf('scout.asia') > -1`.

**Pull request merged**
